# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Admin.create( :first_name => 'Admin',
              :email => 'admin@admin.com',
              :password => 'admin123',
              :password_confirmation => 'admin123')
Client.create!([{:id=>1,:firstname=>'Arkadiusz Kalisz uslugi remontowe',:order_id=>1},
                {:id=>2,:firstname=>'Marzena Cieślak',:order_id=>2},
                {:id=>3,:firstname=>'Andrzej Dziedzic',:order_id=>3},
                {:id=>4,:firstname=>'Natalia Hanulak',:order_id=>5},
                {:id=>5,:firstname=>'Starostwo Powiatowe w Wieluniu',:order_id=>6},
                {:id=>6,:firstname=>'Tadeusz Zych',:order_id=>7},
                {:id=>7,:firstname=>'abm DESIGN Mateusz Bydałek',:order_id=>8},
                {:id=>8,:firstname=>'Piekarnia s.c. Nowakowscy',:order_id=>9},
                {:id=>9,:firstname=>'Ewa Paszek',:order_id=>10},
                {:id=>10,:firstname=>'Karolina Chmura',:order_id=>11},
                {:id=>11,:firstname=>'Mirosław Jakubowski',:order_id=>12},
                {:id=>12,:firstname=>'Usługi Ogolnobudowlane Paweł Golik',:order_id=>13},
                {:id=>13,:firstname=>'Mateusz Sprezyna',:order_id=>14},
                {:id=>14,:firstname=>'Grzegorz Niziałek',:order_id=>15},
                {:id=>15,:firstname=>'Dawid Szydłowski',:order_id=>16},
                {:id=>16,:firstname=>'Adam Hetman',:order_id=>17},
                {:id=>17,:firstname=>'Grzegorz Torchalski',:order_id=>18},
                {:id=>18,:firstname=>'Melania Wierzycka vel Kryger',:order_id=>19},
                {:id=>19,:firstname=>'Dariusz Michalczak',:order_id=>20},
                {:id=>20,:firstname=>'Kowol Arkadiusz',:order_id=>21},
                {:id=>21,:firstname=>'Andrzej Drobek',:order_id=>22},
                {:id=>22,:firstname=>'Arkadiusz Banaś',:order_id=>23},
                {:id=>23,:firstname=>'Mateusz Bryjok',:order_id=>24},
                {:id=>24,:firstname=>'Joanna Jankowska',:order_id=>25},
                {:id=>25,:firstname=>'New Smile Georges Popela stomatolodzy sp.p.',:order_id=>26},
                {:id=>26,:firstname=>'Krzysztof Siemieniuch',:order_id=>27},
                {:id=>27,:firstname=>'Krzysztof Roś',:order_id=>28},
                {:id=>28,:firstname=>'Mieczysława Zema',:order_id=>29},
                {:id=>29,:firstname=>'Roman Kłodziński',:order_id=>30},
                {:id=>30,:firstname=>'Daniel Darnowski',:order_id=>31},
                {:id=>31,:firstname=>'Przedsiębiorstwo Handlowo - Usługowe DANEX Sp. z o.o. Sp. K.',:order_id=>32},
                {:id=>32,:firstname=>'Euro-car Łukasz Ziółkowski',:order_id=>33},
                {:id=>33,:firstname=>'Wioletta Litwinowicz',:order_id=>34},
                {:id=>34,:firstname=>'Radosław Czapiewski',:order_id=>35},
                {:id=>35,:firstname=>'Wioleta Miotk',:order_id=>36},
                {:id=>36,:firstname=>'Joanna Maj',:order_id=>37},
                {:id=>37,:firstname=>'Dorota Chat',:order_id=>38},
                {:id=>38,:firstname=>'Damian Ciszek',:order_id=>39},
                {:id=>39,:firstname=>'Pomorska Grupa Czystości i Dozoru Sp. z o.o.',:order_id=>40},
                {:id=>40,:firstname=>'Dorota Banasik',:order_id=>41},
                {:id=>41,:firstname=>'Dariusz Kubara',:order_id=>42},
                {:id=>42,:firstname=>'PAWEŁ SZCZEPANIAK',:order_id=>43},
                {:id=>43,:firstname=>'KONSBUD2 SP.Z.O.O. SP.KOMANDYTOWA',:order_id=>45},
                {:id=>44,:firstname=>'Ochotnicza Straż Pożarna',:order_id=>46},
                {:id=>45,:firstname=>'Konserwacja i Naprawa Urządzeń Alarmowych Sławomir Łuczak',:order_id=>47},
                {:id=>46,:firstname=>'Krzysztof Maśliński',:order_id=>48},
                {:id=>47,:firstname=>'Piotr Wójcicki',:order_id=>49},
                {:id=>48,:firstname=>'Robert Końca',:order_id=>50},
                {:id=>49,:firstname=>'FHiU "WITNIA"',:order_id=>51},
                {:id=>50,:firstname=>'Jan Warot',:order_id=>52},
                {:id=>51,:firstname=>'Agata Wójtowicz',:order_id=>53},
                {:id=>52,:firstname=>'Ryszard Drewniak',:order_id=>54},
                {:id=>53,:firstname=>'Jadwiga Dąbek',:order_id=>55},
                {:id=>54,:firstname=>'Wojciech Ciupak',:order_id=>56},
                {:id=>55,:firstname=>'Łukasz Olborsk',:order_id=>57},
                {:id=>56,:firstname=>'ANNA BARWIAK',:order_id=>58},
                {:id=>57,:firstname=>'KLIMA-DRAGUN KRZYSZTOF DRAGUN',:order_id=>59},
                {:id=>58,:firstname=>'Radosław Kozakiewicz',:order_id=>60},
                {:id=>59,:firstname=>'Krzysztof Serafin',:order_id=>61},
                {:id=>60,:firstname=>'Jacek Stucke',:order_id=>62},
                {:id=>61,:firstname=>'piotr papiż',:order_id=>63},
                {:id=>62,:firstname=>'Radosław Bogdanowicz',:order_id=>64},
                {:id=>63,:firstname=>'Arkadiusz Bożek',:order_id=>65},
                {:id=>64,:firstname=>'Daniel Kusz',:order_id=>66},
                {:id=>65,:firstname=>'Wioletta Kratiuk',:order_id=>67},
                {:id=>66,:firstname=>'Krzysztof Goiński',:order_id=>68},
                {:id=>67,:firstname=>'Norbert Kubicki',:order_id=>69},
                {:id=>68,:firstname=>'Kamil Kaszuba',:order_id=>70},
                {:id=>69,:firstname=>'Marek Piwko',:order_id=>71},
                {:id=>70,:firstname=>'Marzena Korus',:order_id=>72},
                {:id=>71,:firstname=>'P.P.H.U. KAR-BET',:order_id=>73},
                {:id=>72,:firstname=>'Krystian Woźny',:order_id=>74},
               ])
Adress.create!([{:id=>1,:client_id=>1,:company_street=>'Kunegundy',:company_number=>'14/9',:company_zip=>'33-300',:company_city=>'Nowy Sącz',:company_nip=>'7343555244'},
                {:id=>2,:client_id=>2,:company_street=>'Targowisko',:company_number=>'5',:company_zip=>'63-210',:company_city=>'Żerków'},
                {:id=>3,:client_id=>3,:company_street=>'Skołyszyn',:company_number=>'405',:company_zip=>'38-242',:company_city=>'Skołyszyn'},
                {:id=>4,:client_id=>4,:company_street=>'Henrykowo',:company_number=>'6/1',:company_zip=>'64-100',:company_city=>'Henrykowo'},
                {:id=>5,:client_id=>5,:company_street=>'Plac Kazimierza Wielkiego',:company_number=>'2',:company_zip=>'98-300',:company_city=>'Wieluń'},
                {:id=>6,:client_id=>6,:company_street=>'Kawka',:company_number=>'50',:company_zip=>'21-025',:company_city=>'Niemce'},
                {:id=>7,:client_id=>7,:company_street=>'Długa',:company_number=>'6',:company_zip=>'64-610',:company_city=>'Rogoźno',:company_nip=>'7661811851'},
                {:id=>8,:client_id=>8,:company_street=>'Wolska',:company_number=>'7',:company_zip=>'95-054',:company_city=>'Ksawerów',:company_nip=>'7311748106'},
                {:id=>9,:client_id=>9,:company_street=>'Pojdy',:company_number=>'21c',:company_zip=>'44-213',:company_city=>'Rybnik'},
                {:id=>10,:client_id=>10,:company_street=>'Mikołaja Trąby',:company_number=>'12a/111',:company_zip=>'03-146',:company_city=>'Warszawa'},
                {:id=>11,:client_id=>11,:company_street=>'Krosnowice',:company_number=>'182',:company_zip=>'57-362',:company_city=>'Krosnowice'},
                {:id=>12,:client_id=>12,:company_street=>'B.Chrobrego',:company_number=>'6B/9',:company_zip=>'49-300',:company_city=>'Brzeg',:company_nip=>'7471674090'},
                {:id=>13,:client_id=>13,:company_street=>'lipowiec',:company_number=>'61',:company_zip=>'23-407',:company_city=>'Tereszpol'},
                {:id=>14,:client_id=>14,:company_street=>'Wrocławska',:company_number=>'29/15',:company_zip=>'67-100',:company_city=>'Nowa Sól'},
                {:id=>15,:client_id=>15,:company_street=>'Zbiczno',:company_number=>'105',:company_zip=>'87-305',:company_city=>'Zbiczno'},
                {:id=>16,:client_id=>16,:company_street=>'Przy Stadionie',:company_number=>'1',:company_zip=>'83-210',:company_city=>'Zblewo'},
                {:id=>17,:client_id=>17,:company_street=>'Leśna',:company_number=>'8',:company_zip=>'97-371',:company_city=>'Wola Krzysztoporska'},
                {:id=>18,:client_id=>18,:company_street=>'Szaforza',:company_number=>'1',:company_zip=>'42-700',:company_city=>'Lubliniec'},
                {:id=>19,:client_id=>19,:company_street=>'Korabina',:company_number=>'53',:company_zip=>'37-433',:company_city=>'Bojanów'},
                {:id=>20,:client_id=>20,:company_street=>'Wilsona',:company_number=>'121',:company_zip=>'44-190',:company_city=>'Knurów'},
                {:id=>21,:client_id=>21,:company_street=>'Migdałowa',:company_number=>'3',:company_zip=>'65-160',:company_city=>'Zielona Góra'},
                {:id=>22,:client_id=>22,:company_street=>'Grochowice',:company_number=>'84',:company_zip=>'67-240',:company_city=>'Kotla'},
                {:id=>23,:client_id=>23,:company_street=>'Pokoju',:company_number=>'92/94',:company_zip=>'43-140',:company_city=>'Lędziny'},
                {:id=>24,:client_id=>24,:company_street=>'Nowa',:company_number=>'12',:company_zip=>'87-850',:company_city=>'Czerniewice'},
                {:id=>25,:client_id=>25,:company_street=>'Opawska',:company_number=>'40',:company_zip=>'47-400',:company_city=>'Racibórz',:company_nip=>'6392013442'},
                {:id=>26,:client_id=>26,:company_street=>'Toruńska',:company_number=>'11a',:company_zip=>'86-050',:company_city=>'Solec Kujawski'},
                {:id=>27,:client_id=>27,:company_street=>'Jaworówka',:company_number=>'18',:company_zip=>'05-270',:company_city=>'Marki'},
                {:id=>28,:client_id=>28,:company_street=>'Krasickiego',:company_number=>'13/16',:company_zip=>'37-200',:company_city=>'Przeworsk'},
                {:id=>29,:client_id=>29,:company_street=>'Kalsko',:company_number=>'62',:company_zip=>'66-300',:company_city=>'Międzyrzecz'},
                {:id=>30,:client_id=>30,:company_street=>'Ligi Polskiej',:company_number=>'2a/54',:company_zip=>'87-100',:company_city=>'Toruń'},
                {:id=>31,:client_id=>31,:company_street=>'Dworcowa',:company_number=>'34',:company_zip=>'64-730',:company_city=>'Wieleń',:company_nip=>'7632111476'},
                {:id=>32,:client_id=>32,:company_street=>'Toruńska',:company_number=>'108',:company_zip=>'87-800',:company_city=>'Włocławek',:company_nip=>'8882682418'},
                {:id=>33,:client_id=>33,:company_street=>'Kłodzka',:company_number=>'38/1',:company_zip=>'57-340',:company_city=>'Duszniki-Zdrój'},
                {:id=>34,:client_id=>34,:company_street=>'Radosna',:company_number=>'11',:company_zip=>'76-251',:company_city=>'Łosino'},
                {:id=>35,:client_id=>35,:company_street=>'Pucka',:company_number=>'53',:company_zip=>'84-104',:company_city=>'Jastrzębia Góra'},
                {:id=>36,:client_id=>36,:company_street=>'Marglowa',:company_number=>'59',:company_zip=>'26-600',:company_city=>'Radom'},
                {:id=>37,:client_id=>37,:company_street=>'Wojska Polskiego',:company_number=>'41/6',:company_zip=>'48-300',:company_city=>'Nysa'},
                {:id=>38,:client_id=>38,:company_street=>'Kamieniec',:company_number=>'31',:company_zip=>'34-471',:company_city=>'Ludźmierz'},
                {:id=>39,:client_id=>39,:company_street=>'Gen. Jarosława Dąbrowskiego',:company_number=>'4',:company_zip=>'81-754',:company_city=>'Sopot',:company_nip=>'5851464831'},
                {:id=>40,:client_id=>40,:company_street=>'Kopernika Mikołaja',:company_number=>'62/50',:company_zip=>'90-553',:company_city=>'Łódź'},
                {:id=>41,:client_id=>41,:company_street=>'Wyzwolenia',:company_number=>'92',:company_zip=>'42-425',:company_city=>'Pradla'},
                {:id=>42,:client_id=>42,:company_street=>'TACZAKA',:company_number=>'25',:company_zip=>'64-360',:company_city=>'Zbąszyń'},
                {:id=>43,:client_id=>43,:company_street=>'A.Konstanty',:company_number=>'29/20',:company_zip=>'33-300',:company_city=>'Nowy Sącz',:company_nip=>'7343516379'},
                {:id=>44,:client_id=>44,:company_street=>'PASZKI DUŻE',:company_number=>'64',:company_zip=>'21-300',:company_city=>'Radzyń Podlaski',:company_nip=>'5381799160'},
                {:id=>45,:client_id=>45,:company_street=>'Czarnieckiego',:company_number=>'17',:company_zip=>'98-220',:company_city=>'Zduńska Wola',:company_nip=>'8291312316'},
                {:id=>46,:client_id=>46,:company_street=>'Rucewo',:company_number=>'7',:company_zip=>'88-180',:company_city=>'Złotniki Kujawskie'},
                {:id=>47,:client_id=>47,:company_street=>'Gen. Józefa Bema',:company_number=>'1/1',:company_zip=>'58-570',:company_city=>'Jelenia Góra'},
                {:id=>48,:client_id=>48,:company_street=>'Okrężna',:company_number=>'36',:company_zip=>'74-100',:company_city=>'Wirów'},
                {:id=>49,:client_id=>49,:company_street=>'Kraszewskiego',:company_number=>'73',:company_zip=>'33-380',:company_city=>'Krynica-Zdrój',:company_nip=>'7342645666'},
                {:id=>50,:client_id=>50,:company_street=>'zaborze',:company_number=>'35a',:company_zip=>'32-090',:company_city=>'Słomniki'},
                {:id=>51,:client_id=>51,:company_street=>'Jelenin',:company_number=>'14A',:company_zip=>'74-500',:company_city=>'Chojna'},
                {:id=>52,:client_id=>52,:company_street=>'Konary',:company_number=>'77',:company_zip=>'63-910',:company_city=>'Miejska Górka'},
                {:id=>53,:client_id=>53,:company_street=>'Dwernickiego',:company_number=>'46/50m1',:company_zip=>'87-100',:company_city=>'Toruń'},
                {:id=>54,:client_id=>54,:company_street=>'Trzebuska',:company_number=>'133',:company_zip=>'36-050',:company_city=>'Sokołów Małopolski'},
                {:id=>55,:client_id=>55,:company_street=>'Krawczyka Mariana',:company_number=>'7',:company_zip=>'02-495',:company_city=>'Warszawa'},
                {:id=>56,:client_id=>56,:company_street=>'OGRODOWA',:company_number=>'1',:company_zip=>'66-131',:company_city=>'CIGACICE'},
                {:id=>57,:client_id=>57,:company_street=>'WIEJSKA',:company_number=>'73',:company_zip=>'32-800',:company_city=>'Brzesko',:company_nip=>'8732890316'},
                {:id=>58,:client_id=>58,:company_street=>'Lisów',:company_number=>'74A',:company_zip=>'21-100',:company_city=>'Lubartów'},
                {:id=>59,:client_id=>59,:company_street=>'Rydzów',:company_number=>'63B',:company_zip=>'39-300',:company_city=>'Rydzów'},
                {:id=>60,:client_id=>60,:company_street=>'Suleckiego',:company_number=>'2a/54',:company_zip=>'87-100',:company_city=>'Toruń'},
                {:id=>61,:client_id=>61,:company_street=>'kurów',:company_number=>'34/3',:company_zip=>'72-001',:company_city=>'Kołbaskowo'},
                {:id=>62,:client_id=>62,:company_street=>'Wełmice',:company_number=>'54',:company_zip=>'66-627',:company_city=>'Wełmice'},
                {:id=>63,:client_id=>63,:company_street=>'Wyszyńskiego Stefana',:company_number=>'52/11',:company_zip=>'50-331',:company_city=>'Wrocław'},
                {:id=>64,:client_id=>64,:company_street=>'powst wlkp',:company_number=>'8',:company_zip=>'62-720',:company_city=>'Brudzew'},
                {:id=>65,:client_id=>65,:company_street=>'Olszowa',:company_number=>'8A',:company_zip=>'05-120',:company_city=>'Legionowo'},
                {:id=>66,:client_id=>66,:company_street=>'Jana III Sobieskiego',:company_number=>'4',:company_zip=>'62-500',:company_city=>'Konin'},
                {:id=>67,:client_id=>67,:company_street=>'Zastawie',:company_number=>'43',:company_zip=>'26-026',:company_city=>'Bilcza'},
                {:id=>68,:client_id=>68,:company_street=>'Gdańska',:company_number=>'4/36',:company_zip=>'91-066',:company_city=>'Łódź'},
                {:id=>69,:client_id=>69,:company_street=>'Lwowska',:company_number=>'131',:company_zip=>'22-600',:company_city=>'Tomaszów Lubelski',:company_nip=>'9211516900'},
                {:id=>70,:client_id=>70,:company_street=>'Bestwinska',:company_number=>'21/7',:company_zip=>'43-502',:company_city=>'Czechowice-Dziedzice'},
                {:id=>71,:client_id=>71,:company_street=>'Sportowa',:company_number=>'39',:company_zip=>'86-105',:company_city=>'Świecie5591349428'},
                {:id=>72,:client_id=>72,:company_street=>'Piękna',:company_number=>'60ae/4',:company_zip=>'50-506',:company_city=>'Wrocław',:company_nip=>''},
               ])
