# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
#
#Morris.Line
#  element: 'products_chart'
#  xkey: 'created_at'
#
#  ykeys: [ 'price' ]
#  labels: [ 'price' ]
#  lineColors: [
#    '#2A3F54'
#  ]
#  data: $('#products_chart').data('products'),
#    resize: true

# ---
# generated by js2coffee 2.2.0


# ---
# generated by js2coffee 2.2.0
